FROM nginx
MAINTAINER SinoGear Group

RUN rm -rf  ./usr/share/nginx/html/*
COPY dist/.  . /usr/share/nginx/html/


COPY nginx.conf  ./etc/nginx/nginx.conf


RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
&& echo 'Asia/Shanghai' >/etc/timezone

